@REM Maven wrapper batch script for Windows.
@REM Do not edit this file; it is managed by the Maven Wrapper plugin.
@echo off
setlocal

set SCRIPT_DIR=%~dp0
set MAVEN_WRAPPER_PROPERTIES=%SCRIPT_DIR%.mvn\wrapper\maven-wrapper.properties

for /f "tokens=2 delims==" %%a in ('findstr /i "distributionUrl" "%MAVEN_WRAPPER_PROPERTIES%"') do set DISTRIBUTION_URL=%%a

set MAVEN_HOME=%USERPROFILE%\.m2\wrapper\dists\%~n0

if not exist "%MAVEN_HOME%" (
    echo Downloading Maven from %DISTRIBUTION_URL% ...
    mkdir "%MAVEN_HOME%"
    powershell -Command "Invoke-WebRequest -Uri '%DISTRIBUTION_URL%' -OutFile '%MAVEN_HOME%\maven.zip'"
    powershell -Command "Expand-Archive -Path '%MAVEN_HOME%\maven.zip' -DestinationPath '%MAVEN_HOME%'"
    del "%MAVEN_HOME%\maven.zip"
)

for /r "%MAVEN_HOME%" %%f in (mvn.cmd) do set MVN_EXEC=%%f

"%MVN_EXEC%" %*
